### ISSUE TITLE
Integrate the radical keyboard also in the create/edit custom deck

### ISSUE THREAD

**Issue by WAPEETY** [SYtor/Kanji-Dojo#10]
The Kanji selection to make custom sets doesn't work, I tried writing in kana and the whole kanji but nothing to select appears, also, wouldn't be a great idea to implement also in this section the search by radicals "keyboard"?

Btw, great app if you need help I'm here

**Comment by syt0r** [comment]
Hi. Are you referring to "Create" screen? Which version are you using, google play or fdroid? It works for me on google play version

![image](https://user-images.githubusercontent.com/7478653/221401838-36a4a71b-5ad5-420e-abaf-0331cc9377d9.png)

And regarding radicals, you want to have a text field to enter radical, right?

**Comment by WAPEETY** [comment]
> Hi. Are you referring to "Create" screen? Which version are you using, google play or fdroid? It works for me on google play version
> 
> ![image](https://user-images.githubusercontent.com/7478653/221401838-36a4a71b-5ad5-420e-abaf-0331cc9377d9.png)
> 
> And regarding radicals, you want to have a text field to enter radical, right?

I'm using F-droid version

**Comment by WAPEETY** [comment]
![Screenshot_20230226-102020_Kanji Dojo](https://user-images.githubusercontent.com/38016769/221402304-5ac5ed39-8498-45fe-8e76-09b0e4638e7f.jpg)
![Screenshot_20230226-101809_Kanji Dojo](https://user-images.githubusercontent.com/38016769/221402308-21f8648d-5e71-49b7-8c26-428d770a9a70.jpg)

**Comment by syt0r** [comment]
Just tried FDroid version, both Create and Edit screen works for me, very weird. Non japanese characters are filter out and if some japanese characters are not in database, like 卌, it should show dialog.

Can you please try to rotate screen after entering input and clicking on search button? Maybe visual state is not updated properly

**Comment by WAPEETY** [comment]
Ok, so... sorry it's just that I was trying to add characters by pressing the send button after typing 😅 

Second "request" about the radical keyboard it could be an enhancement :)

**Comment by syt0r** [comment]
Ah, I see what you did here, I guess it would be nice to handle keyboard's submit button as well 👍. These are nice suggestions, I might implement them in the next verision or after the next

**Comment by WAPEETY** [comment]
> Ah, I see what you did here, I guess it would be nice to handle keyboard's submit button as well +1. These are nice suggestions, I might implement them in the next verision or after the next

If you want I can try to make a pull request... it shouldn't be a lot of work

**Comment by syt0r** [comment]
Sure, I would appreciate it. You can take keyboard submit feature, input field should be somewhere in CreateWritingPracticeScreenUI.kt

**Comment by syt0r** [comment]
I noticed you tried to handle this in your branch but didn't succeed. If you still interested here is a hint - carefully look at the parameters of `BasicTextField` method, it should be handled as a search input, ctrl + left mouse click on the method to see more

**Comment by WAPEETY** [comment]
thanks, yes I tried but I didn't put so much effort, this weekend I'll try again :)

**Comment by syt0r** [comment]
I think there's no reason to have an input field to select radicals

**Comment by WAPEETY** [comment]
wait, if I remember well the final idea was to make it work with the submit button
