### ISSUE TITLE
Feature request: Hiding one random section in review mode 

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#104]
This function can be one of the toggles in the review settings screen.

One (one, not more) of the following red sections can randomly hide, say, with 5% probability. It can help to not remember kanji only by translation (as I do).

![IMG_20240208_030433.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/1dad0be0-f424-4aa3-a6cc-794f3b44c9f3)

I know that there is the "No translation layout" toggle, this function can be something like an intermediate stage between "Full translation" and "No translation"

**Comment by Audman** [comment]
Alternative method:
Hide the translation block after N correct writings in a row. Will help to not get confused while reviewing old and new kanjis.

**Comment by syt0r** [comment]
Sorry, but this is quite weird feature, it's complicated and I don't think people will use it much. You can already use no translation layout mode and practice part of your review queue in a similar way to what you described
