### ISSUE TITLE
Let the "Done" label cover all the known characters, not only the unreviewed ones.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#120]
As I've described this matter [here](https://github.com/syt0r/Kanji-Dojo/issues/70), it could be of a great help to be able to quickly launch the practice of all already known characters from the given set, regardless of characters being reviewed or not yet. This way one can train the whole learned set every day, much quicker than by constantly selecting all the known characters by hand.

I kindly kindly please to consider this :) .

**Comment by syt0r** [comment]
What about the chart?

**Comment by ThomasLeigh** [comment]
> What about the chart?

What do you mean?

**Comment by syt0r** [comment]
'Done' label covers green part of the chart, there will be a conflict with 'due' label if 'done' will include both sets

**Comment by ThomasLeigh** [comment]
> 'Done' label covers green part of the chart, there will be a conflict with 'due' label if 'done' will include both sets

**Thank you for pointing this out.** First I thought that maybe would it be all right to make that green part to represent all the known characters (done + unreviewed). I'm not sure would this be all right for you, though...

**Another idea** is to add one more label ("Known"). Or at least add some button in the screen with the set's character list...?

You know, when you introduced the merge feature, I used it to merge all the grades I've already completed. Now I have one great character set including all my done grades - I use it for SRS, to master the missing percentage of my accuracy levels.

Alongside this big set I still have and practice all the grades separately, without SRS, but one day whole grade 1, another day whole grade 2, etc.

On top of that every day I practice all the learned characters from the grade I'm in the process of learning (so also without SRS). Plus 5 new Kanji every day.

To have a closer look on how all of this is going accuracy level-wise, I use Track and Graph ( https://github.com/SamAmco/track-and-graph ; if you would be willing to incorporate - very useful - accuracy graphs into Kanji Dojo, it definitely would look much better than within Track and Graph, because your whole GUI is aesthetic and elegant).

Besides everything else, learning Kanji has an entertaining, relaxing, and even meditative aspect for me - therefore I don't confine myself to SRS only. So selecting dozens of characters by hand every day may be also a part of that, hmm..., meditative experience, rotfl ;) . But if there would be the ability to instantaneously launch the practice of all already known characters - It definitely be of a great help :) .

**Comment by ThomasLeigh** [comment]
I'd like to thank You for introducing "Due" and "Done" checkboxes, alongside with the possibility to check both of them at once - which finally allows me to quickly select all the characters I already know, whether they are scheduled for spaced repetition or not. It significantly helps with the everyday routine.

**Comment by syt0r** [comment]
Hm, after all I don't think there should be more buttons there, that menu should stay compact and concise and all most necessary things are already there so I would prefer to keep it as is design-wise
