### ISSUE TITLE
Wrong stroke count for some radicals on search screen

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#124]
These guys are definitely more than 2 strokes

![Screenshot_2024-04-05-02-16-52-463_ua.syt0r.kanji.fdroid-edit.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/9fb60e2f-659e-4c28-b1ee-5fe6767751de)

**Comment by syt0r** [comment]
Right... there is some additional info specifically for these radicals in radkfile but I don't understand why they have wrong stroke count. I'll probably remove them and add more preprocessing to not show radicals that don't have any characters in database

**Comment by syt0r** [comment]
Fixed in version 2.0.4
