### ISSUE TITLE
Too many radicals in the kanji viewer

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#133]
For example here it's a ton of radicals, and most of them are the same or combinations of other ones:

![Screenshot_2024-05-08-23-44-33-956_ua.syt0r.kanji.fdroid.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/0d59823f-d94c-4c70-94dd-2a6941083791)

It'd be more simple if there were only 咸 and 心, clickable. 
And if you need more information for example about 咸, just click and open another page.

**Comment by syt0r** [comment]
Right, seems like some radicals get partially annotated multiple times, I can display only distinct characters. I can make them clickable, but I'm not sure that all radicals can be found in database, especially ones that are not kanji on their own

**Comment by syt0r** [comment]
Fixed in version 2.0.5
