### ISSUE TITLE
Could Secondary School Kanji also be split into particular grades?

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#136]
Could Secondary School Kanji also be split into particular grades,  as in case of Grade 1-6?

**Comment by ThomasLeigh** [comment]
@syt0r Yesterday I've finished Grade 6 Kanji. Now I'm in trouble ;) because all the rest Kanji Jouyou are gathered within one large set. Over the time I've created my own routine of practice, in which I periodically draw whole grades (one day Grade 1, another day Grade 2, and so on). I also do SRS, but drawing whole sets is important part of my practice.

Now, it could be of a great help to have all the rest Kanji Jouyou also split into separate sets (like in case of Grade 1 - 6). Or to have the ability to split any particular set into smaller ones (the opposite function to the Merge). A user could define the part's size (for example, Jouyou beyond Grade 6 could be split into five 222-character sets).

For now unfortunately I need to remove hundreds of characters, one by one, by hand, in order to have such a result :( .

Could you please help with that?

**Comment by syt0r** [comment]
You can copy-paste characters from [here](https://github.com/syt0r/Kanji-Dojo/blob/e864960aefb6cb8b0462ca41fed0792e60684e3c/core/src/commonMain/kotlin/ua/syt0r/kanji/core/japanese/CharacterClassification.kt#L185C11-L185C32) into a custom set

This set is quite large, but it was classified like this in original data source. It can be divided into smaller ones by some random numbers, but it's not even the biggest set, N1 is even bigger, and it's not very clear how to pick a suitable number of characters per set. I want to improve edit screen though, primarily to make it easier to select multiple characters to reset their review progress, so it might help with this issue in future

**Comment by ThomasLeigh** [comment]
@syt0r

> it's not very clear how to pick a suitable number of characters per set.

You know, I wanted to continue learning Kanji sets per school grade in order to feel like a true Japanese :) , at least to some degree :) . So I was ready to take the challenge even if those sets would be bigger. 

But unfortunately there are no grades above 6th - and I don't know why. Besides, it's not clear to me how many grades indeed do exist above the 6th. I'd love to know.

Thank you for your help with pointing out the place from which I can copy further characters. I divided them into five 222-character sub-sets, so it fits me enough. Although it's sad I don't know how Japanese themselves learn these characters above grade 6th :( .

Thanks to You, however, I am now fortunately able to have further sets of relatively acceptable size :) . Thank you very much.

**Comment by syt0r** [comment]
I couldn't find any classification with more details for grades above 6 so I'll close this issue
