### ISSUE TITLE
autoplay always turned off by default

### ISSUE THREAD

**Issue by AminurAlam** [SYtor/Kanji-Dojo#137]
whenever starting new hiragana/katakana practice session autoplay turns off, and it has to be tuned on every new practice session because it forgets its last state

version 2.0.4 fdroid release

https://github.com/syt0r/Kanji-Dojo/assets/64137875/89a27ce1-4364-4d60-b1ad-f2fddf1aa5bd

**Comment by syt0r** [comment]
Hey, thanks for letting me know, you're right, it's only saved on writing practice screen

**Comment by AminurAlam** [comment]
thanks for the fix
