### ISSUE TITLE
Vocabulary practice UI: answers don't fit by length

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#141]
![Screenshot_2024-05-27-18-16-12-438_ua.syt0r.kanji.fdroid.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/e3857567-110c-4565-a459-edb1068891e3)

The answers should be like a list, not like a table. 

![Screenshot_2024-05-27-18-18-57-909_ua.syt0r.kanji.fdroid.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/e7955d32-d9d5-4c7b-8412-67279a0fe4c7)

In the vertical view they also don't fit.

**Comment by Audman** [comment]
Also, about the colors. 
There are 水色,茶色,全色 and similar phrases where the hidden kana is 色. Shouldn't it be better if the hidden kana was on the other kanji? (水,茶,全...)

**Comment by syt0r** [comment]
In this particular case it looks like a lot of empty space, I agree. There are probably additional button paddings making text ere break lines, I guess I could try to make text smaller to some extent if it doesn't fit

About colors I agree as well. My intention was to randomly pick all kanji if there's any, but for something like colors I guess it makes sense to hardcode some additional rules for word readings that end with 色. There are probably more cases like this. I wonder if it can get tricky to create such rules for kana readings too if there will be custom word decks in the app

**Comment by syt0r** [comment]
Length issue was fixed in previous version
