### ISSUE TITLE
Larger GUI font.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#145]
In the ver. 2.0.5 I've noted that font is smaller, for example on practice summary screen:

![Screenshot_2024-06-04-12-22-21-150_ua syt0r kanji fdroid](https://github.com/syt0r/Kanji-Dojo/assets/26142231/42a9f319-bedc-4cf6-ae22-3224ce93aebd)

**Would it be all right for you to restore larger font?** It was more convenient for the weaker eye vision.

It would be fantastic to be able to somehow enlarge font size **throughout the whole app's GUI**. I know it may be problematic sometimes, but it could make a difference for users with weaker vision. I'm aware that probably this is a very limited user group but maybe you would be willing to consider this matter.

**Comment by syt0r** [comment]
I don't think I've changed anything there in the last version, maybe only some spacings between text, and titles have pretty big size there already, I'm not sure I can help with it if changing system's font size doesn't help
