### ISSUE TITLE
"Pair" kanjis in practice

### ISSUE THREAD

**Issue by polandreh** [SYtor/Kanji-Dojo#146]
When practicing a set, kanjis are shuffled randomly every time we want to practice (if the option is selected).

However, depending on the set, it would make more sense if certain kanjis can be grouped so that they stick together during the shuffling.

For example, I have a practice relating to food. So, 
菓, 米, 果, 菜, 豆, 卵, 肉, etc. But 海苔 (nori) is a jukujikun, so 海 (sea) and 苔 (moss) by themselves don't work in this list.

Could we create a custom pair or group with our own expressions and hints so that we can practice them consecutively?

Maybe, we could have a "group" editor or object section where we can create these bundles of kanji, and add the groups in practice sets along with single characters.

**Comment by syt0r** [comment]
I can see some reason in this, but kanji in existing sets pretty much don't have any common context. I think it would make more sense for users to create custom sets if they want to review kanji with some specific context. Moreover, it would require categorizing a lot of kanji. I don't think there're a lot of benefits considering efforts

But this gave me another idea that I find more useful - creating kanji sets based on vocab sets. It will encourage learning vocab as well as kanji with similar context. Maybe a feature to post and view user created kanji and vocab sets withing the app could help with it too

**Comment by syt0r** [comment]
There are related issues #154 and #210 so I'm closing this one
