### ISSUE TITLE
Suggestion: Easier way to select all groups

### ISSUE THREAD

**Issue by MailYouLater** [SYtor/Kanji-Dojo#15]
I'd like to have a way to review all groups without having to manually select each and every individual group.

This could be accomplished by allowing the user to start a review with zero groups selected, and interpret that the same as if they had selected all groups (possibly with verification), or by adding select/deselect all buttons.

![Screenshot](https://user-images.githubusercontent.com/1279475/222950477-ce2152f2-c653-46e9-a342-2000fa95b51a.jpg)

**Comment by syt0r** [comment]
I already implemented select/deselect all buttons in my local branch, it will be part of the next release

**Comment by syt0r** [comment]
Done, available in version 1.2
