### ISSUE TITLE
Restore selection state on deck details screen after data refresh

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#155]
Everyday I learn 5 new Kanji. I need to repeat the selected 5 few times. In order to do that earlier on, once I finished practice and returned to the character list, **those five characters remained selected,** so I needed just to tap red confirmation button on the right bottom corner to practice those characters again.

Now, however, the previously selected characters do not remained selected after finishing their practice :( .

Could the previous behaviour be restored? Or maybe a button to repeat the last character selection be added?

**Comment by syt0r** [comment]
I see, I remade that screen in scope of one of the recent features and removed this extra logic, I'll try to keep selection after refreshing screen's data

**Comment by ThomasLeigh** [comment]
Thank You very much it works again ;) ! Highly appreciated.
