### ISSUE TITLE
[Bug] Calendar Text Spacing is broken

### ISSUE THREAD

**Issue by FelicityIris** [SYtor/Kanji-Dojo#158]
Bug Behavior: The numbers on the 7th day of the week are broken as illustrated in the attached file.

Attachment:
![Screenshot_20240702_222606_Kanji Dojo.jpg](https://github.com/syt0r/Kanji-Dojo/assets/77635620/71ae64b1-3d03-4f89-8aa0-5806126e2d95)

App Version: `2.0.7`

Device: `Samsung Galaxy M34 5G`

OS: `Android 14`, `One UI 6.1`

Additional Note: All font related settings are unchanged, and factory default.

**Comment by syt0r** [comment]
Should be fixed in version 2.1.0
