### ISSUE TITLE
Crash when opening 艹 radical

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#163]
When I tap this button, the app crashes 

![Screenshot_2024-07-17-16-31-26-252_ua.syt0r.kanji.fdroid-edit.jpg](https://github.com/user-attachments/assets/ec9b551b-b451-4988-8f45-e9400709bd5d)

**Comment by syt0r** [comment]
Thanks for the report. It doesn't have any readings in database and my new layout doesn't handle this case properly

**Comment by syt0r** [comment]
Fixed in version 2.0.9
