### ISSUE TITLE
Practice preview screen configuration indicator 

### ISSUE THREAD

**Issue by syt0r** [SYtor/Kanji-Dojo#17]
Configuration turned out very extensive but there is almost no distinction within user interface so it might get confusing which configuration is currently used

Planning to add a line above list with information about practice type - whether it's writing or reading, filtering and sorting

**Comment by Audman** [comment]
I recommend adding a left-handed tablet mode, so you can write without covering expressions with your hand.

**Comment by syt0r** [comment]
@Audman good idea, created #21 for it

**Comment by syt0r** [comment]
Available in version 1.3
