### ISSUE TITLE
Filter button disappears after filtering only for due

### ISSUE THREAD

**Issue by Felix248** [SYtor/Kanji-Dojo#173]
I don't know how to explain it so I'll do it with screenshots.

1.
![Screenshot_20240724-092954~2](https://github.com/user-attachments/assets/f5b103a6-b0cd-44f0-89aa-3695aabfdd25)

2.
![Screenshot_20240724-093019~2](https://github.com/user-attachments/assets/1ffe96bc-7c31-421d-9093-1d7b90542c7b)

3.
![Screenshot_20240724-093123~2](https://github.com/user-attachments/assets/a73882d6-d0e6-4b2b-bf56-6c7c7b154142)

4. All buttons at the top (including the filter button) just disappear
![Screenshot_20240724-093146~2](https://github.com/user-attachments/assets/495c3a0f-30ce-4e44-9824-2393d7d5b29f)

You can get it back by switching the view to single characters.

**Comment by syt0r** [comment]
I see, this is a huge issue, I didn't think about it, thanks for letting me know. It's great there's a workaround, I'll fix it soon

**Comment by syt0r** [comment]
Fixed in version 2.0.9
