### ISSUE TITLE
App crashing bug due to time overflow

### ISSUE THREAD

**Issue by Ddragon1000** [SYtor/Kanji-Dojo#176]
Hey there,

this is a great app with all the features I need. Great work. I especially like the custom vocabulary lists which I almost exclusively use and is usually missing in even good paid apps. I like this implementation of yours a lot.
However, since the introduction of the "Again" to "Easy" rating system I have the bug, that when I looked at a Kanji like 3 times and finally click enough times on "Good" or "Easy" (after using "Again" and "Hard" a few times) the Time system overflows. Like easy was at first 3 days, then 14 days, then 900 days and afterwards it overflows to -1100492 seconds. All options are like this (progressively more negative) except the "Again" option with 5 minutes. (See Attachments.)
That would be fine because I don't care about the time that is written there, but this overflow makes it impossible to complete a session due to the app crashing after like 3 symbols after the selection of a single negative number.
I am using the newest version of both Kanji-Dojo and Android.

Thanks in Advance!

![Screenshot_20240812-154202.png](https://github.com/user-attachments/assets/80e7448b-dbbf-42a6-80bd-dc04f7bcdc1e)

**Comment by syt0r** [comment]
I see, maybe this is why fsrs has max interval configuration in their implementation. Thanks for the report

**Comment by sirjofri** [comment]
I also regularly encounter this bug and it seems you can work around it by clicking the "Again (5m)" button once. This seems to recalculate the number and store a proper value, future encounters of the word/character show proper time values.

That said, I assume that you can click any "real" time value to reset it, but I only tried the "Again" button. At least, it lets me finish the current session.

**Comment by syt0r** [comment]
Looks like there was a serious issue and the app messed up the stability and difficulty parameters for fsrs algorithm after getting them from database. I also added interval limit to be safe. Tested it a bit and it seems to solve the issue. I'll try to release the next version with this fix later this week if there won't be any other major issues

**Comment by syt0r** [comment]
Fix is available in version 2.1.0, feel free to reopen if it still happens
