### ISSUE TITLE
Ability to save database outside of app

### ISSUE THREAD

**Issue by AntiApple4life** [SYtor/Kanji-Dojo#179]
Having the ability to save the two databases (`kanji_data.sqlite` and `user_data.sqlite`) in an accessible folder would be a useful feature. It would allow syncing between multiple devices via Sync thing, which would be a great stopgap between now and a custom sync server.

**Comment by syt0r** [comment]
Overall `kanji_data` is shipped with the app so there's no need to sync it. This feature make sense but I'm planning to make a paid online sync option in the future so please use the backup feature for sharing your progress across devices
