### ISSUE TITLE
Too long repeating periods

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#180]
![Screenshot_2024-09-01-23-31-36-149_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/d3669170-b6ba-47c8-9836-aef0b981789b)

In the screenshot there are somewhat too big periods for repeating kanjis. 

![Screenshot_2024-09-01-23-37-59-031_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/11464a0e-3a2d-4111-b626-2d809fe9dc09)

They show up as some big numbers and don't change, even if I write the kanji wrong several times. 

Shouldn't the periods start with some certain number and slowly lower while the user is making mistakes?

**Comment by syt0r** [comment]
I was following the implementation of fsrs scheduler in Go and parameters for the algorithm weren't updated when cards have relearning status, but seems like the last week they updated it and now params are getting updated in this case as well, so I guess it was a bug and I should fix it too...

**Comment by stbotman** [comment]
Actually, I faced the same problem, but I can hypothesize about why this could happen. In previous versions several times I encountered negative times in time till next repeat followed by a crush. Perhaps it's related?
Maybe adding an option in menu to reset history to some sane default would solve the issue?
I didn't dig into this though, just some educated guesses.

**Comment by syt0r** [comment]
Released an update, now intervals are more adjustable but they still might be quite big by default, I'll think about other potential adjustments that can be made
