### ISSUE TITLE
Writing box overlaps examples on Galaxy Z Fold 5

### ISSUE THREAD

**Issue by AntiApple4life** [SYtor/Kanji-Dojo#185]
When practicing kanji, the writing box overlaps the example list. This is a minor issue, but I still wanted to report it.
![Screenshot_20240907_101306_Kanji Dojo](https://github.com/user-attachments/assets/8945f701-305c-41bc-9a35-8445bff52979)

**Comment by syt0r** [comment]
It works as expected, the list in the background should be scrollable, allowing you too see info if needed. Or do you think that the input section is too big?

**Comment by AntiApple4life** [comment]
My only worry is that when the example word is longer, the writing box could cut off part of the example word. It seems like an edge case, though. Maybe shrinking the writing box on those edge cases would be a solution

**Comment by syt0r** [comment]
I don't think it will cover all edge cases even if I shrink it a little. By the way, very interesting device, does the app has same layout in portrait and landscape orientations? In landscape mode it should split screen into 2 panes, with details and input to the sides. Maybe using the app with landscape orientation would be a better experience with this type of screen

**Comment by AntiApple4life** [comment]
> I don't think it will cover all edge cases even if I shrink it a little. By the way, very interesting device, does the app has same layout in portrait and landscape orientations? In landscape mode it should split screen into 2 panes, with details and input to the sides. Maybe using the app with landscape orientation would be a better experience with this type of screen

It does split on landscape, and works well that way
