### ISSUE TITLE
Letter reading practice should not hide charecter from expressions list

### ISSUE THREAD

**Issue by runarberg** [SYtor/Kanji-Dojo#186]
I love the v2.1.0 changes to the letter reading practice. Particularly I love how currently all the expressions are presented, rather than just the first 5. However there is no need to hide the target character from those expressions as we already see it above. Instead of hiding the character it would be better to hide the translation, the translations often give away the answer if I’m trying to remember the meaning of the character. And better, if there would be an extra button to reveal the translation, such that I could first recall the meaning, than reveal the translation before remembering the reading.

To illustrate, this is the current screen (before revealing answer):

> **住**
> 
> Expressions (33)
> ⃝む - to live (of humans)
> ⃝宅 - residence
> ⃝民 - inhabitant
> ⃝所 - address
> 在 ⃝ - residence 
>
> [Show Answer]

This is what I propose instead:

> **住**
>
> Expressions (33) [show translations]
> 住む
> 住宅
> 住民
> 住所
> 在住
> 
> [Show Answer]

This change would allow me to practice both the meaning and the reading of the kanji at the same time

**Comment by syt0r** [comment]
Hmm, looks like the same issue as #191 which was fixed so I'm closing this one too
