### ISSUE TITLE
Allow to hide timing on answer ratings buttons.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#187]
Could You please allow it?

**Comment by syt0r** [comment]
I don't think it's a good idea, not for the SRS mode at least, but I'm planning to add a non srs practice mode in future

**Comment by ThomasLeigh** [comment]
> I don't think it's a good idea, not for the SRS mode at least, but I'm planning to add a non srs practice mode in future

Note that some users prefer not to be distracted by timing info during graded practice. Besides, it's much clearer then. Anki allows users to choose whether timing should be included in answer buttons or not. This can make more Kanji Dojo users satisfied.

![Screenshot_2024-09-11-12-49-38-973_com.ichi2.anki.jpg](https://github.com/user-attachments/assets/f6100807-6cf9-4289-8f48-67f19683137a)

![Screenshot_2024-09-11-12-49-20-802_com.ichi2.anki.jpg](https://github.com/user-attachments/assets/f0cd0dc5-b265-470d-90af-c3fa989a112c)

**Comment by ThomasLeigh** [comment]
@syt0r I'm just asking for the choice: that users who prefer timing on answer buttons would have it - while users for whom it's a distraction, would be able to disable it.
