### ISSUE TITLE
Answer ratings buttons not fully visible.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#188]
Maybe it's due to that I use larger font in Android. Can it be adjusted for all the buttons to nicely fit within the visible area?

![Screenshot_2024-09-08-22-13-40-227_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/3f86413f-29de-45d2-ac27-e35f1b557bf2)

**Comment by ThomasLeigh** [comment]
![Screenshot_2024-09-09-15-44-53-637_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/8f549147-8bcb-49ce-8ebd-66ba20ed89b9)

**Comment by syt0r** [comment]
This is expected behavior, you can scroll the row to the side. It doesn't look great, I agree, but sometimes it doesn't fit even without increased font scaling. I think it's better than making text on the buttons break lines unnaturally and make buttons cover writing area even more

**Comment by ThomasLeigh** [comment]
@syt0r Could You please at least center answer buttons? It will reduce the risk to need to scroll it.
