### ISSUE TITLE
[Bug] Decks are sorted by the last letter review time and not the deck review time

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#189]
Earlier on it was independent from any characters scheduled for repetition. If, for example, I've drawn the whole grade 5 Kanji 5 days ago, but **today** Kanji Dojo gave me - among others - some grade 5 characters to exercise - once I've done the exercise, **the grade 5 as a whole set stays still with "5 days ago" last review time**. This allows to nicely sort whole sets, day by day, with fixed order - **which is especially important is you draw whole sets routinely.**

Now it seems it is no longer possible, because it seems that if you draw some characters scheduled for today practice, **their whole mother sets' last review time is affected.**

**Could You please restore character sets last review time to independent from charters appointed repetitions?**

**Comment by syt0r** [comment]
Yes, seems like there's a bug there, I'm redoing that part for the next update so it will be fixed. But note that the last deck review time will be updated when starting reviews from the home screen, time will be updated for the top most deck that contains the reviewed letter

**Comment by ThomasLeigh** [comment]
> Yes, seems like there's a bug there, I'm redoing that part for the next update so it will be fixed. But note that the last deck review time will be updated when starting reviews from the home screen, time will be updated for the top most deck that contains the reviewed letter

Could you do deck last review time dependent **only** from practicing it fully? In other words. deck last review time is about the deck **as a whole -** it should be updated only when the deck has been fully practiced.

**Comment by syt0r** [comment]
It could be done, but decks aren't fully reviewed very often, so I think sorting the decks manually shouldn't be too much of a problem

**Comment by ThomasLeigh** [comment]
> It could be done, but decks aren't fully reviewed very often, so I think sorting the decks manually shouldn't be too much of a problem

The thing is I draw one full grade each day (grade 1, 2, 3.... and back again) and thanks to previous sort logic I hadn't need to look for the proper deck to practice for today **because it had always been placed on the very bottom.**

**Lack of that undisturbed sort logic eliminates the everyday convenience** and sense of sorting whole decks by last review time, especially for students who practice whole decks. As a result, now I often need to check in the other app which full deck I practiced yesterday.

**Comment by ThomasLeigh** [comment]
@syt0r Could you please restore decks last review time as dependent only from their full practice?

**Comment by syt0r** [comment]
It can be made as an extra sorting option in future, but I can't make it as a default behavior, otherwise regular users might have decks sitting for months in the list marked as not reviewed at all

**Comment by ThomasLeigh** [comment]
> It can be made as an extra sorting option in future

**Would You please add such a sorting?** It makes a big difference for me, it was a great improvement when long time ago You've introduced sorting sets by last review time, it made a big big difference, the everyday practice had been much more seamless thanks to this very thing, because I didn't need to wonder or remind myself each and every time what set I've done last time. The proper set to practice had been always on the very bottom.

**Comment by syt0r** [comment]
Fixed in version 2.1.2, you can open a new feature request for the new sorting method

**Comment by ThomasLeigh** [comment]
@syt0r Thank You very much :) ! It makes a big difference.
