### ISSUE TITLE
Is scheduling characters for months really ok?

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#190]
Before FSRS 2.1.0 I've usually have something between **50-90** characters assigned by Kanji Dojo for me **daily**, as due for practice.

Now I have just **a ten and a few...** and I've noticed that some characters are **scheduled for months (!!!).**

All of this worries and disturbs me. Is it really all right that way?

**Comment by ThomasLeigh** [comment]
![Screenshot_2024-09-11-14-46-35-211_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/7d0955a0-4f70-4b60-9f40-5faeedc578c0)

**Comment by syt0r** [comment]
It happened due to migration to the new algorithm, previous one was way more stricter so intervals can get quite big by default after migration. I don't think there's anything I can do, you can use the Again button during review to bring it down
