### ISSUE TITLE
[Bug] Letter reading practice displays translations in hidden state

### ISSUE THREAD

**Issue by 1Piwix0** [SYtor/Kanji-Dojo#191]
In prior versions, english translations could be configured to only appear after revealing the answer in reading practice. Now in version 2.1.0 english translations are always visible.

**Comment by syt0r** [comment]
Yes, it is a mistake, translations are supposed to be hidden initially, I'll fix it in the next version

**Comment by syt0r** [comment]
Fixed in version 2.1.2
