### ISSUE TITLE
No continue button after writing the kanji

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#20]
This bug happens sometimes. Maybe the reason is too fast writing.

- My device: Poco X4 GT
- Android version: 13
- MIUI version: 14

https://user-images.githubusercontent.com/88189119/224990304-cae32545-2cf0-4a13-8e30-43eb194323df.mp4

**Comment by syt0r** [comment]
Hey, thank you for report. This is definitely a bug, I will investigate it

**Comment by syt0r** [comment]
Hopefully it's just an UI bug, so meanwhile if it happens again you can try to rotate screen or toggle dark mode, it should let you continue with practice

**Comment by Audman** [comment]
Yes, it works!
I tried to write the next part before the animation of the previous part ended, and it happened again.

https://user-images.githubusercontent.com/88189119/225136174-1a75e3ad-4895-48d7-a3a8-c2d04bf1a565.mp4

**Comment by syt0r** [comment]
Should be fixed in version 1.3
