### ISSUE TITLE
Bug: disable daily limit doesn't work

### ISSUE THREAD

**Issue by Skivling** [SYtor/Kanji-Dojo#201]
In version 2.1.2, after adding many new features to the daily limit it has been broken - If I disable the Daily Limit using the toggle switch at the top, then press save it won't actually disable it and when I go back onto the page it is enabled again.

Expected behaviour: after the toggle is switched off and Save is pressed, it should properly save it and disable Daily Limit.

**Comment by leekleak** [comment]
Can confirm. Same goes both ways actually - I had daily limit disabled before the update and I'm no longer able to enable it.

**Comment by syt0r** [comment]
Right, I forgot to save the toggle value after all changes there, I'll try to release new update with this fix soon

**Comment by syt0r** [comment]
Fixed in 2.1.3
