### ISSUE TITLE
Unable to distinguish single kana words in reading picker mode

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#203]
Some of the words have only hiragana or even better, just one kana like this: 

![Screenshot_2024-09-26-10-12-29-383_ua.syt0r.kanji.fdroid.jpg](https://github.com/user-attachments/assets/0d074d55-7a91-47a1-9491-655f425dd1e4)

I think it should be better if a word has only hiragana the translation should be visible

**Comment by syt0r** [comment]
Yeah, kana words can definitely be tricky, having multiple valid words for given options, I guess I'll have to change description for "Show meaning" configuration too

**Comment by syt0r** [comment]
Fixed in 2.1.3
