### ISSUE TITLE
Alternate romanization of ぢ and づ

### ISSUE THREAD

**Issue by jgierer12** [SYtor/Kanji-Dojo#22]
In the app, both じ and ぢ are romanized as `ji`, and both ず and づ are romanized as `zu`. The same applies to ジ / ヂ and ズ / ヅ . While this makes sense because they're both pronounced the same, it creates confusion when you need to differentiate between them, such as when trying to quickly practice kana.

To avoid this issue, ぢ and づ are sometimes romainzed as `di` and `du`, because that was their original pronunciation. This is also the way you type them when using a romaji IME. So I think it would be great if this app also had an option to use `di` and `du` for ぢ / ヂ and づ / ヅ .

**Comment by syt0r** [comment]
This is definitely should be updated in the next version. Thank you for report

**Comment by syt0r** [comment]
Available in version 1.3
