### ISSUE TITLE
No update in fDroid

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#31]
I watched the repo today and found out, that there are two new versions of the app.
Is it alright that there are no updates in fDroid?

**Comment by syt0r** [comment]
This is expected, it might take several days for fdroid servers to detect new update

**Comment by syt0r** [comment]
There is an issue after all, tried to manually update it there but it failed. Something is wrong with reproducible builds, so latest update won't be available on fdroid. Hopefully I will be able to fix it by the next version. It's ok to use last fdroid build from github releases page, next versions will be compatible

**Comment by syt0r** [comment]
New version was successfully published on fdroid :tada:
