### ISSUE TITLE
Change practice configuration buttons behavior 

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#32]
These buttons are opening the same menu:
![Screenshot_2023-03-29-18-50-42-082_ua.syt0r.kanji.fdroid-edit.jpg](https://user-images.githubusercontent.com/88189119/228611631-294af1a3-9405-402a-9c89-9e977ec0b02b.jpg)

It'd be better to change the first two buttons' values on tap, without any menus.
The sorting button should open only this part:
![Screenshot_2023-03-29-18-55-30-273_ua.syt0r.kanji.fdroid-edit.jpg](https://user-images.githubusercontent.com/88189119/228613290-b1988224-3a28-4229-acd9-61a5b2782b6d.jpg)

That will make the interface more simple.

**Comment by syt0r** [comment]
Good suggestion. I didn't touch this dialog but with new UI it can definitelly be updated

**Comment by Audman** [comment]
Addition: filter button should open another menu with checkboxes
- Show completed kanjis
- Show kanjis to repeat
- Show new kanjis

For example, I want to practice repeat and new kanjis only, not completed ones.

**Comment by syt0r** [comment]
Updated in version 2.0.4
