### ISSUE TITLE
Bad translation of 里

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#34]
![SAVE_20230403_202048.jpg](https://user-images.githubusercontent.com/88189119/229594031-cf4d132c-6abe-4964-8c4b-0fa3778c25da.jpg)

The main translation is just onyomi of the kanji. 
It should be "village" for example.

**Comment by syt0r** [comment]
Hm, characters info is from kanjidic, but there is also entry in jmdict dictionary for 里 and "ri" actually means "Japanese league, old Japanese unit of distance, approx. 3.927 km or 2.44 miles". I agree that "village" would be more appropriate, though it would require implementing solution to override dictionary priorities

**Comment by Audman** [comment]
Also on topic: 
市 should be first "city" and then "town" and "market", because most of it's words mean something related to cities:
![Screenshot_2023-04-21-01-43-01-575_ua.syt0r.kanji.fdroid.jpg](https://user-images.githubusercontent.com/88189119/233508947-1ce55f4e-7acb-4ede-baab-31589d0fb54c.jpg)

Also, Chinese cities end with 市:
![Screenshot_2023-04-21-01-45-43-239_com.google.android.apps.maps.jpg](https://user-images.githubusercontent.com/88189119/233509210-f685b9fb-a93b-4faf-ac8a-6b08ab478b3f.jpg)

**Comment by syt0r** [comment]
里 was fixed, but for 市 I think it can be left as is, other dictionaries also have it in first place
