### ISSUE TITLE
Clickable radicals on kanji page

### ISSUE THREAD

**Issue by Stesyo** [SYtor/Kanji-Dojo#36]
Hello, it would be really helpful if clicking at radical opened a subpage about it (the same behaviour when you click at kanji in Expressions tab).
![image](https://user-images.githubusercontent.com/108234495/230975019-6c857449-4fa2-4511-b746-a55c55c2e4a2.png)

**Comment by ThomasLeigh** [comment]
I definitely agree. It would be very helpful to have that ability - plus to quickly show all characters with a given (tapped) radical.

Any chances for these features?

**Comment by syt0r** [comment]
Fixed in version 2.0.5
