### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by zeromero-dev** [SYtor/Kanji-Dojo#37]
Dark theme to allow users who study at night to harm their eyes a little less than usual.

TAG: **enchancment**

**Comment by syt0r** [comment]
Do you mean existing dark theme is too bright or that there is no dark theme applied on your device?

**Comment by zeromero-dev** [comment]
There's actually no ***dark theme*** option for me at all.
Using version from Play Market dated as 28th of March.
![S30424-101328(1)](https://user-images.githubusercontent.com/55024478/233924833-b4804159-de0e-4dc3-a6e1-ad8dbdb13eb0.jpg)

**Comment by syt0r** [comment]
It's automatically enabled when your system is using dark theme, there is no option in the settings. What Android version do you have?

**Comment by zeromero-dev** [comment]
> It's automatically enabled when your system is using dark theme, there is no option in the settings. What Android version do you have?
<br/>
v8.1.0
<br/>
But for the sake of UX it's better to add a switch in options menu.

**Comment by syt0r** [comment]
Hm, seems like system dark theme mode was introduced only in Android 10, makes sense to add manual toggle then

**Comment by syt0r** [comment]
This feature will be present in the next release, although idk when it will get released
