### ISSUE TITLE
Enable kanji compound (expressions) practice

### ISSUE THREAD

**Issue by adaerr** [SYtor/Kanji-Dojo#39]
Hi, to help make the step from individual kanji learning to learning common expressions, it would be great if there was a mode that, instead of presenting a subset of selected kanji for revision, presented a subset of expressions written with the selected kanji. For example, for a user choosing to review expressions written with JLPT N5 kanji, the app might show the hiragana/furigana for «nihon» , possibly the english meaning «Japan», and expect the two kanji to be drawn successively on the sketch surface. Could mix kanji/hiragana as well e.g. for verbs or adjectives.

(Great app, thanks!)

**Comment by syt0r** [comment]
I see, this mode might have some potential, but would be quite tricky implement and I'm not sure how many users will want to use it. 

Basically it would test both writing and reading knowledge, but at the same time all possible kanji reading won't be covered during practice so it can't be counted as reading practice, but only writing.

I'll leave it open and if there won't be any more important features in my mind and free time I'll consider implementing it

**Comment by dren39** [comment]
Hi there, just wanted to add that I very much also second this suggestion. This would be a great way to level up learning. Thanks for your work.

**Comment by syt0r** [comment]
Looks like the vocab practice mode that was added some time ago solves this issue

**Comment by adaerr** [comment]
Yes very good, thanks a lot!
(originally wanted practice mode that automatically aggregates all words formed using already known/practiced kanji, but building vocab lists manually is fine too!)

**Comment by adaerr** [comment]
(looking forward to issue #154 with the possibility to restrict to `done' characters as mentioned in comment!)
