### ISSUE TITLE
Hide On and Kun readings during practice writing mode

### ISSUE THREAD

**Issue by dren39** [SYtor/Kanji-Dojo#41]
Hi, I know this suggestion overlaps with the reading mode a bit but I wanted to ask if it's possible to add the option to hide the On and Kun definitions during practice writing mode, the same way the kanji is hidden, until the kanji is correctly written or when a reveal button is tapped? Personally, I don't use the reading mode very much. I like to test my On and Kun reading while doing the writing practice, and I'd have to physically cover up the On and Kun readings with my thumb until I'm ready to move onto the writing.

**Comment by Audman** [comment]
Another mode, hide translations and show only Japanese text (on and kun readings, word examples)
Like this:

![IMG_20231018_221754.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/1d04edba-ca5f-430d-8248-31c777b51da6)

![IMG_20231018_221527.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/cf3396f3-7bd6-4bfb-b8e5-7fc5a59ad1d8)


Or even like this:

![IMG_20231018_222328.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/bf7c54ad-6038-4e10-a071-4a851e9c0c76)

**Comment by dren39** [comment]
Ideally, I'd like to be able to hide the On and Kun definitions and only show the english definitions so that I can test my memorization while practicing the writing.

**Comment by syt0r** [comment]
I see. I mainly added an option to hide translations since they are at the top and I kept focusing on translations rather than readings. Honestly, I have some doubts if this mode is useful since readings have a very important role

**Comment by dren39** [comment]
I understand. Just thought I'd suggest it since it was something that came up everyday. Thanks for taking a look at this.
