### ISSUE TITLE
Crash when 'Search by radical' menu is open and navigate to another tab

### ISSUE THREAD

**Issue by dren39** [SYtor/Kanji-Dojo#42]
Steps to reproduce:

1. Go to the Search tab 
2. Tap on the kanji next to the search input to open the "search by radicals" menu
3. Navigate away from the Search by tapping either the Practice or Settings tab
4. Tap on the Search tab again. App will freeze and crash.

**Comment by syt0r** [comment]
Oops, forgot to reply, it was a known issue of the framework, hopefully after libraries update it was fixed in latest versions
