### ISSUE TITLE
Radical search bug?

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#43]
I was searching for the 猫 kanji. I selected two radicals, and the last radical was blocked.

![Screenshot_2023-08-12-18-57-35-288_ua.syt0r.kanji.fdroid-edit.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/61041bf1-85b3-4ef1-9335-10a49999f435)

**Comment by syt0r** [comment]
Interesting, it can be an issue with kanji vg, need to take a closer look, thanks for report

**Comment by syt0r** [comment]
The app is now using radicals from radkfile, and I believe this case is not present there so I'm closing this issue
