### ISSUE TITLE
Enhancement Request: Allow an option to sort the practices in the main page

### ISSUE THREAD

**Issue by polandreh** [SYtor/Kanji-Dojo#52]
When creating the practices, they are sorted in the order in which they were created. If we want to rearrange them, we'd need to delete them and recreate them in the order we want them.

An Edit option to move them to a different order would be more flexible, allowing us to move down practices we no longer need to review that often, bringing the new ones to the top.

**Comment by syt0r** [comment]
I agree, I had this feature in mind as well. Although I'm using pretty big practice sets it already feels not very convenient after a while. Maybe I could add a button to the top bar to initiate reordering

**Comment by MailYouLater** [comment]
Similar to #13, drag & drop would be ideal, but if that's not feasible, another method would of changing the order would still be much better than the current inability to do so.

**Comment by syt0r** [comment]
Implemented for version 1.9
