### ISSUE TITLE
Backup / Restore. 

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#56]
It would be of a great help and importance to be able to backup and restore the user's character sets in order to be able to smoothly continue learning and practice on (e.g.) another device or once the current device has been factory-reset.

**Comment by polandreh** [comment]
I was thinking of something similar or related. I've shown this app to the people in my Japanese class, and it would be very useful to share the practices we've made, rather than have them all build them again one by one.

Maybe an export file that you can share with others via email or WhatsApp?
