### ISSUE TITLE
groups size

### ISSUE THREAD

**Issue by vpassama** [SYtor/Kanji-Dojo#59]
Hi,

Thanks for the app, it's great !
More of a suggestion than an issue.
When I'm working on groups of hiragana, I would find it easier if they'de be sorted as groups of 5 instead of 6, like this I would be able to learn for example (a u i e o) without the ka which would remain with ku ki ke ko and so on.

Maybe you could add an option to edit groups size or groups content.

Thanks for reading.

**Comment by syt0r** [comment]
I agree that practice groups with 6 characters are not very suitable for kana. I think it would be best to have a custom layout for kana practice, but having an option to customize group sizes is also a nice feature. 

I'm planning to add more view options there to be able to see scheduled review dates for each character so I might implement this as well

**Comment by vpassama** [comment]
I've tried the updated app and now kanji are in groups of 5 so that's fine for me and this issue is no longer needed from my point of view. Should I close it myself or do you need it for further dev ? Thank you.

**Comment by syt0r** [comment]
Great, I'm closing it then
