### ISSUE TITLE
Daily goal causes some confusion

### ISSUE THREAD

**Issue by nab4444** [SYtor/Kanji-Dojo#60]
I'm quite new to the app and I seem to struggle to understand how daily goal works

For example I want to have 30 kanji for reading practice and 30 kanji for writing practice (i want to do both on the same day), if i set my goal to 30, I do 30 kanji for one type of training and the goal is complete, if I set my goal to 60, then by pressing quick practice it does all 60 in a row

It would make more sense if we could either set separate goals for each type of practice or select an amount of reps to do when starting a quick practice.

**Comment by syt0r** [comment]
I was expecting that users would learn using only one mode at a time, but I understand your take. I need to think about how to make it better without being too complicated, some people already confuse things according to reviews in Google Play. So yes, right now quick practice will exhaust all daily limits with only one mode if there's enough character there

I might add more options to the daily goal configuration dialog, or maybe some additional dialog with a cog button next to quick practice to decrease characters amount to practice. Or even some slider on the practice configuration menu to practice partially

**Comment by nab4444** [comment]
That would be great! I think that practicing with both modes is great, taking into account how well the reading mode is. It feels bad to miss out on reading practice when doing writing!

**Comment by syt0r** [comment]
Added slider to practice configuration in version 1.7 so you can select half of the characters when you use quick practice menu
