### ISSUE TITLE
Donation does not work

### ISSUE THREAD

**Issue by madpipeline** [SYtor/Kanji-Dojo#61]
I tried to make a donation.

Paypal won't allow me: `In order to respect international reglementations this transation was rejected`
Direct with the card: `Something went wrong. We will take you back to the checkout page to try again`

I tried several times and it won't let me.

I assume both go through paypal and there's some weird policy in place right now.

Have you considered https://liberapay.com ? It's working via Paypal or Stripe.

**Comment by syt0r** [comment]
Hey, thanks for letting me know, I've never received donations before. Unfortunately, librepay is not supported in my country. 

Did you try to donate via https://www.paypal.com/donate/?hosted_button_id=TC36DKW7S8NB2 ? I'm not seeing any activity in Paypal so I'm not sure what's going on. 

Paypal only recently allowed to receive payments in my country, maybe these types of transactions are not allowed. I'll investigate this further, maybe I'll have to switch donation platform

**Comment by madpipeline** [comment]
I have tried. I get stuck at the confirmation code that I'm supposed to receive via SMS. The SMS never comes. I have retried several times, even tried to have them call me.

Just curious, what country are you from?

**Comment by syt0r** [comment]
It's in my profile :) Thanks for trying, I appreciate it

**Comment by syt0r** [comment]
Removed donation options for now, maybe I'll add them later on, don't want to deal with it right now
