### ISSUE TITLE
Option to select individual kanji to learn from group instead of whole 6 items subgroups

### ISSUE THREAD

**Issue by seppiola** [SYtor/Kanji-Dojo#62]
Hi, I would like to suggest to add an option to select individual kanji to learn from the practice groups and in an arbitrary number in addition of using the current 6 items subgroups with not easily rearrangeable order (according to what was said in previous issues discussion I understand reordering is not feasible at the moment).

As of now the only way to "learn" a kanji (at least as I am aware of) is to do it in whole subroups batches or with the quick learn button on a practice group, both of which won't let you choose the kanji to learn (the first method would only let you select subgroups, of which you can rearrange the order only by frequency, name or addition order).

I'm actually using a workaround at the moment but is far from ideal: I create a temporary custom practice group with the kanji I want, "learn" the whole group, and then delete it an subsequently use the quick review on the bigger practice groups that contains the kanji I just learned.

An other option could be to let the user "learn" a kanji with a button in its info page, not ideal for batches but it still leaves the possibility to learn the kanji you want.

I want to say regardless that I like the way the app is taking shape, and of course its openess and that I would try to at least provide further feedback as I continue to use it.

**Comment by syt0r** [comment]
You can select characters one by one now in version 1.7
