### ISSUE TITLE
saving progress

### ISSUE THREAD

**Issue by JunkyardCat** [SYtor/Kanji-Dojo#65]
so when im doing the learn kanji thing and want to back out of it in the middle do i need to do it all over again? so i have like tried to study around 300 kanji today but when i stopped and press back it still says i have the same amount of kanji(blue number) as i have started with.

**Comment by syt0r** [comment]
I've never tried to do a practice with so many characters at once, do you reach the summary screen where total practice time, accuracy and other things are shown? If you didn't reach that screen then results won't be saved

**Comment by JunkyardCat** [comment]
@syt0r 
no i didnt reach the screen where the save button can be found

**Comment by syt0r** [comment]
You need to complete practice for it to be saved. If you minimized the app and left it unattended for a long time then the system might have killed it and you lost all of the progress. I don't recommend to practice so many characters at once, try to do multiple smaller sessions instead
