### ISSUE TITLE
During practice: make Android back button return from expressions list

### ISSUE THREAD

**Issue by neithernut** [SYtor/Kanji-Dojo#66]
During practice of a kanji, the app shows a few expressions containing that kanji and lets you pop up a longer list of expressions. However, due to UI glitches[^1] I sometimes fail to return to the actual practice. Currently (version 1.6) the back-button will abort the practice directly (after asking for confirmation). Making the Android back button first close the list (as an alternative to the flicking gesture which, in my case, doesn't always work) would probably help in such situations and thus lead to less aborted practices and less frustration.

[^1]: which I found to be somewhat prevalent in the practice view, honestly. I suspect the input will sometimes go to the wrong layer.

**Comment by syt0r** [comment]
What exactly is this glitch? Does app stops reacting to your touch while bottom sheet panel fills whole screen or is it just top panel that should be dragged goes out of the screen? I hope that app doesn't freeze and still responsive in this state, can you still click on expressions? For now you can try to rotate the screen (e.g. from portrait to landscape mode), it will probably let you continue with your practice. But yeah, it's fairly easy to handle back button click, I just want to ensure it will really fix the issue

**Comment by neithernut** [comment]
Thanks for the quick reply!

> What exactly is this glitch? Does app stops reacting to your touch while bottom sheet panel fills whole screen or is it just top panel that should be dragged goes out of the screen?

The panel listing the expressions (2 in the screenshot below) doesn't fill the entire screen, but most of it. Flicking gestures and dragging will sometimes have some effect on the portion underneath it, which is visible through the topmost portion (1 in the screenshot) not covered by the sheet.
![screenshot](https://github.com/syt0r/Kanji-Dojo/assets/6747556/d99e8784-123b-4cef-afc2-854a9cb744ed)
Note: the UI behaved correctly when I took the screenshot. I also scaled the screenshot to half it's original size.


> I hope that app doesn't freeze and still responsive in this state, can you still click on expressions?

Yes, I can still click on expressions, and aborting also still works. Viewing an expression will sometimes restore "normal" UI behavior.

> For now you can try to rotate the screen (e.g. from portrait to landscape mode), it will probably let you continue with your practice.

Thanks for the hint, I'll try this next time I run into the issue.

> But yeah, it's fairly easy to handle back button click, I just want to ensure it will really fix the issue

Thanks!

**Comment by syt0r** [comment]
Implemented in version 1.7
