### ISSUE TITLE
Unable to donate

### ISSUE THREAD

**Issue by NiciTheNici** [SYtor/Kanji-Dojo#67]
Hi, I'm from switzerland and paypal (which kofi uses) is apparently blocked here, still I'd like to donate to this awesome project. 

I'll suggest something like [liberapay](https://liberapay.com/) because it too is Free and Open Source :)

![Screenshot_20231120-160851_Fennec](https://github.com/syt0r/Kanji-Dojo/assets/51826257/f1584b86-4520-451f-8fe0-d000bbf1cb56)

**Comment by syt0r** [comment]
Thanks for trying, but I've recently removed all donation options for now #61 Did you follow the link from fdroid? I didn't update it there yet

**Comment by unchartedpopsicle** [comment]
I can confirm that the link on f-droid gives me the reported errors in Norway. This app is fantastic, thank you!

**Comment by madpipeline** [comment]
Since #61 is now closed, I'll comment here: 

I found https://opencollective.com which seems promising, but it's another US based platform, and seemingly it won't allow payments towards occupied regions or Ukraine. Most likely they just blocked the whole country for now.

**Comment by madpipeline** [comment]
@NiciTheNici Unfourtanelty liberapay uses Stripe or Paypal behind the scenes. None of these platforms support payment thowards Ukraine: https://liberapay.com/about/global

**Comment by syt0r** [comment]
I've made an account [here](https://buymeacoffee.com/syt0r) at "Buy me a coffee" so if anyone still interested you can donate me there. I hoped to use a donation system from my country that was released recently to avoid additional fees but they decided to target only bloggers
