### ISSUE TITLE
Practice of the learned characters.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#70]
I study new sets of characters by learning 5 items per day. I want to practice daily all the learned characters from the set. It would be of a great help and improvement to allow somehow to quickly select only the learned characters from the set - in order to practice them.

**Comment by syt0r** [comment]
I agree, someone else already requested this feature in other issue #32 I'll replace options with checkboxes for new, in review and completed characters

**Comment by syt0r** [comment]
Labels next to study progress chart are now clickable

**Comment by ThomasLeigh** [comment]
Do you mean in ver. 1.9? Do you mean labels "done", "due", "new"?

**Comment by syt0r** [comment]
The version that just got released today, v2.0, yes

**Comment by ThomasLeigh** [comment]
> The version that just got released today, v2.0, yes

I've just realised that unfortunately the label "Done" refers only to characters without scheduled review (SRS), while what I mean is the ability to immediately begin a practice of all **learned** / **known** characters, regardless of their SRS scheduling. If I have learned, say, 50 characters out of a character set, even if 10 of them have scheduled review, I would like to be able to immediately start a practice of those 50 characters, without a need to manually select them from a list.

It could be very, very helpful. Could you please consider to include this? Maybe by changing the way the label "Done" is working - or by adding another label ("Known", for example).
