### ISSUE TITLE
[Slight UI issue] android native text scaling

### ISSUE THREAD

**Issue by nab4444** [SYtor/Kanji-Dojo#72]
When using android native text scaling feature, the calendar on the stats screen slides down a bit
Comparison:
![Screenshot_20231213_192951_Kanji Dojo](https://github.com/syt0r/Kanji-Dojo/assets/79978685/17f8d434-98a5-4d5d-baa9-a73e685d4abe)
![Screenshot_20231213_193024_Kanji Dojo](https://github.com/syt0r/Kanji-Dojo/assets/79978685/5fca7180-2533-484b-ac7f-c43ab15e2b63)

**Comment by syt0r** [comment]
I forgot when I fixed this but it's done :sweat_smile:
