### ISSUE TITLE
Enhancement suggestion: Merge kanji banks

### ISSUE THREAD

**Issue by Audman** [SYtor/Kanji-Dojo#73]
It'd be very convenient if I could choose, for example, Wanikani 1-8 and merge them into one bigger bank, instead of 8 separate ones.

![Screenshot_2023-12-13-20-46-38-140_ua.syt0r.kanji.fdroid.jpg](https://github.com/syt0r/Kanji-Dojo/assets/88189119/ec58bb07-7bb8-4085-93d6-2c979d0e71a3)

**Comment by syt0r** [comment]
Implemented in version 1.9
