### ISSUE TITLE
Stroke recognition

### ISSUE THREAD

**Issue by sl08154711** [SYtor/Kanji-Dojo#75]
Sometimes the stroke recognition drives me crazy. When you draw the kanji slowly enough there seems to be less of an issue but if you know some kanji really well and just want to get on with it and draw it more quickly, the app starts to fail to recognize some stroke up to a point where you'd "make" more than two mistakes and have to repeat the character. The whole thing seems to amplified by the fact that I use rugged devices with thick glass (low touch sensitivity). 
Anyway, lately I paid more attention to the recognition and tried to spot situations in which it would fail and I believe the algorithm mostly fails on perfectly horizontal or vertical strokes.
So I though I'd have a peek into the code and I found the following lines of code in DefaultKanjiStrokeEvaluator.kt:

```
        val widthScaleDiff = max(firstScale.width, secondScale.width) /
                min(firstScale.width, secondScale.width)
        val heightScaleDiff = max(firstScale.height, secondScale.height) /
                min(firstScale.height, secondScale.height)

        val relativeScaleError = 5f * (widthScaleDiff + heightScaleDiff)

        val firstScaledToSecond = centeredFirstPoints.scaled(
            scaleX = secondScale.width / firstScale.width,
            scaleY = secondScale.height / firstScale.height
        )
```

These seem problematic to me because `firstScale.width` might be `0`. I'm not sure I follow all the steps in the error estimation but a division by zero is sure to wreck your computation. I never programmed anything in Kotlin but the following could at least rectify the potential division by zero issue. I can't say whether it will improve stroke recognition, though:

```        
        val widthScaleDiff = max(firstScale.width, secondScale.width) /
                max(1.0, min(firstScale.width, secondScale.width))
        val heightScaleDiff = max(firstScale.height, secondScale.height) /
                max(1.0, min(firstScale.height, secondScale.height))

        val relativeScaleError = 5f * (widthScaleDiff + heightScaleDiff)

        val firstScaledToSecond = centeredFirstPoints.scaled(
            scaleX = secondScale.width / max(1.0, firstScale.width),
            scaleY = secondScale.height / max(1.0, firstScale.height)
        )
```

**Comment by sl08154711** [comment]
On second thought, a division by `0` might not ever occur because there might be no perfectly horizontal or vertical strokes but if certain strokes get close enough you might end up dividing by a very small number like `0.00001` which will be even worse because then you effectivly multiply the computed error by several orders of magnitude. Really depends on the data. Also the proposed fix might be syntactically incorrect (don't know Kotlin) and the `1.0` should be changed to a number which will fit the data (a minimum width / height).

**Comment by syt0r** [comment]
Wow, somebody actually took a look at the code :sweat_smile: 

I doubt there might be a 0 over there because it would cause a crash that I could see in google play version's reports. But I noticed some errors as well when drawing strokes too quickly. I can think of two other reasons: less points in quickly drawn strokes which causes rougher approximation or issues with fast strokes submitting (like stroke handling happens slower than input)

I can't tell what exactly is wrong here right now and honestly since its not causing major issues this investigation is low priority for me. Although I can make next button appear regardless of errors count

**Comment by sl08154711** [comment]
You're right. Misrecognition seems to happen primarily with very short (possibly horizontal / vertical) strokes which, of course, have fewer control points. So can it be an issue with Android not sampling the touch screen fast enough? I've tested some settings towards that end but had not much luck. The kanji I struggle with most (inputting; not remembering) are:

- 遺貴: 1st and 4th stroke
- kanji with small enough 口 like 器
- kanji with amigashira like 憲罪買
- some kanji with 門 (5th stroke) like 間簡聞問

Displaying the next button despite of error count would not solve the issue because the kanji would be autoselected for repetition and the "mistakes" would be recorded into the database. Maybe an error threshold depending on the number of control points could help but this would have to be fine tuned which seems like an awful lot of work.

I think this app is phenomenal. It makes learning kanji (or re-learning in my case) a fun exercise and you can learn kanji on the go and not just at home and it saves a ton of paper. But repeating a kanji because of teeny-tine strokes not getting recognised is a bit frustrating. So I do not agree with this issue being low priority because it lowers user retention but I can't think of anything to solve this issue.

**Comment by syt0r** [comment]
It might be inconvenient, sure, but you can still manually mark it as `good` review by clicking on the character on the practice saving page. I've made this feature with manual practice results editing specifically for this case, when stroke recognition algorithm fails. My stroke detection algorithm is quite naive, I'm surprised it works this well at all :sweat_smile: so I'm worried that adjusting it might cause unexpected issues elsewhere

**Comment by sl08154711** [comment]
Yes, inconvenient but no show stopper. That's what I do now. It's just a bit tedious with huge compound lists. I guess we can close this issue for now.

**Comment by syt0r** [comment]
No need, I'll keep this issue and return to it later

**Comment by syt0r** [comment]
Don't want to leave this issue stale so I'm closing it
