### ISSUE TITLE
time tracker counts inactive sessions

### ISSUE THREAD

**Issue by ghost** [SYtor/Kanji-Dojo#76]
When you keep the app running in the background, it continues to track time.

![IMG_20231225_224754](https://github.com/syt0r/Kanji-Dojo/assets/83554212/a3ca236a-c767-46f5-a2ff-0eff97499194)

**Comment by syt0r** [comment]
Yes, I noticed this as well. I might add some cap on review time for every separate character during practice

**Comment by syt0r** [comment]
Implemented in version 1.9
