### ISSUE TITLE
Include Chinese learning alongside Japanese.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#79]
Recently I've begun learning Chinese alongside my current Japanese. So far it's too early to determine will I manage to do such a thing in a long run, but it's definitely exciting, especially given the tangible bond between those two languages (and cultures as well).

If it turns out that I do would be able to learn Chinese with a similar effects as my current Japanese, I must admit that I don't know any app which would be so well-composed and highly well thought out like Yours. The main reasons for me to think that are as follows:

1. Strokes, lines - finally are thick enough (finally, because in many other apps it's very rare, while Your idea to introduce thicker drawings gives the practice more aesthetics and makes it more pheasant experience).

2. Acceptance of the drawings and strokes is imho extremely well-balanced: not too strict (which makes the learning much less stressful and irritating) and still ensuring enough that one has learned the thing.

Now, I'm not so "in the know" regarding Chinese, but given that Japanese is based on Chinese characters I wonder would it be possible to extend Kanji Dojo also for learning the Chinese itself (I mean sole characters, exactly like currently with Japanese in the app)?

I have no idea what challenge it would be for You as a developer and would You be even willing to consider this - but one thing is certain for me: Your app would be especially helpful in such a learning, with all its advantages applied into Chinese language as well.

What do You think?

**Comment by syt0r** [comment]
This idea has already crossed my mind some time ago but it would require a lot of time investments, I'm not even sure if there are open source project with Chinese kanij strokes available and I'm not familiar with Chinese at all. I want to focus on Kanji Dojo first since I'm really interested in learning Japanese, if I ever decide to make an app for other languages it will most likely be a different project
