### ISSUE TITLE
Opening the expressions list sometimes gets stuck and breaks drawing

### ISSUE THREAD

**Issue by Toasterbirb** [SYtor/Kanji-Dojo#81]
I came across an issue where opening the expressions list would make the kanji recognition part of the app to get stuck in a way where you can't draw to parts of the drawing area.

Usually there are some areas that still accept input, but most of the area gets "disabled". In the attached video for example I find one spot at the top left corner where I can draw.

https://github.com/syt0r/Kanji-Dojo/assets/48382422/fbb4a0a2-d12b-4a39-8097-2a8cc8778bf1

I have yet to find a reliable way to cause this bug to happen, but it has something to do with opening the expressions list, because if I don't open it, the drawing bug doesn't manifest. You know that the problem happened when you can't close the expressions list anymore by sliding it down and have to resort to using the android back button.

Some version information:
- App version 1.7, installed from f-droid
- LineageOS 20 (Android 13)

**Comment by syt0r** [comment]
Hmm, weird issue, someone else already encountered a similar issue here #66 Thank you for letting me know

**Comment by syt0r** [comment]
There were a lot of changes and I hope it got fixed so I'm closing this issue, reopen if the bug is still relevant
