### ISSUE TITLE
Usage stats - enable/ disable within settings.

### ISSUE THREAD

**Issue by ThomasLeigh** [SYtor/Kanji-Dojo#82]
I like the idea of usage stats being sent to the developer, I agree it could be valuable source to improve the app.

Shame on me, but I don't remember if I allowed it or not, but I'd like those stats to be enabled. In order to do so I could clear the app's cache but I don't want to lose the progress, all the app's data collected so far. Could You please include sending the app's usage data switch within its settings?

**Comment by syt0r** [comment]
I don't understand what you mean here. Do you want to be able to do backups and restore your progress? There are usage stats that are sent to analytics service right now in google play version of Kanji Dojo, but it's just telling me what features people use and this data can't be fully accessed/used

**Comment by ThomasLeigh** [comment]
When I launched the app the very first time it asked me do I want to allow the app to send its anonymous usage stats to improve its development. I don't remember whether I allowed it or not, but I would like to allow it without clearing the app's data in order to see that question again.

**Comment by syt0r** [comment]
Are you using fdroid version? I removed analytics reports there because my free server was too slow to handle open source self hosted analytics system

**Comment by ThomasLeigh** [comment]
Yes, I use F-Droid version. Thank you for the answer.
