### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [SYtor/Kanji-Dojo#83]
Add material themed app icon

**Comment by Audman** [comment]
Sounds interesting, any ideas?

**Comment by saltsoftdrink** [comment]
@syt0r Kindly reply on this issue

**Comment by syt0r** [comment]
You meant new monochrome icon design from the last android versions, right?)

**Comment by saltsoftdrink** [comment]
> You meant new monochrome icon design from the last android versions, right?)

Yes the monochrome icon it looks neat & clean

**Comment by saltsoftdrink** [comment]
@syt0r Thank You Soo Much
