### ISSUE TITLE
Stroke recognition and answers glitched

### ISSUE THREAD

**Issue by BaranSenkul** [SYtor/Kanji-Dojo#87]
I have recently downloaded this app and started learning some hiragana, while doing my practice, the stroke recognition system and all of the solutions got mixed with the previous question and its order. I'm not really an android app developer so I don't know what causes this. I'm on the lastest app version (play store) and My device is a Galaxy Tab S6 lite running OneUI 5.1(Android 13)
[Here is a video of it](https://youtu.be/hq_fMHpNdOM?si=WFGsKxoCZ_IBhedH)

**Comment by syt0r** [comment]
Thank you for the report, I faced this issue recently as well in the newest version, seems like it's the same issue as #26 and it's the first time I'm seeing this myself. I'm currently updating writing practice logic again so it might fix it for good this time, it's hard to tell why it happens
