### ISSUE TITLE
Suggestion: add a metric showing how many kanjis in total have been reviewed at least once.

### ISSUE THREAD

**Issue by polandreh** [SYtor/Kanji-Dojo#89]
Whenever a kanji is practiced once, there's a green or yellow frame added to it, so there has to be a list of kanjis that have been practiced at least once.

It would be useful to know how many kanjis I have memorized or am in the process of memorizing.

Also, maybe statistics on how many times each kanji has been practiced.

**Comment by syt0r** [comment]
Available since version 1.9
