### ISSUE TITLE
[Suggestion] Import kanji from Wanikani

### ISSUE THREAD

**Issue by wijourdil** [SYtor/Kanji-Dojo#9]
Hi,

First of all thanks for the app!
I would like to make a suggestion, I'm using Wanikani to learn kanji and it would be great to be able to import automatically in the app the kanji I know from the Wanikani API! 

Thanks :)

**Comment by syt0r** [comment]
Hey. Glad you like the app. 

I'm not familiar with wanikani, but from a quick look at the videos on youtube looks like there are kanji grouped by level and levels are not that big, though I'm not sure if it's possible to customize level/create your own

You already should be able to select all characters somewhere on the website and paste them into 'Create practice' screen, all non kana/kanji characters in the input field are ignored.

It would be fairly easy to add additional category to 'Select' screen with wanikani levels. API integration will take much more time to implement, and I'm not sure whether it's reasonable if there are no custom or modified levels on wanikani

Would be glad to hear your opinion on it

**Comment by wijourdil** [comment]
Hi

Yes on Wanikani, kanji are grouped on levels from 1 to 60, and you cannot create your own "levels" or groups of kanji.

I totally understand you might not want to integrate calls to the wanikani API (and so, have to keep it working in the future) in your app :)

I don't think (at least I did not find where) we can copy a list of our learned kanji directly from wanikani
But I have tried to call the API and it's easy to get the list of kanji per level & for a given user

I think I can make a small tool that generates a list of kanji from a given API token, ready to be copied / pasted into your app using 'Create custom practice' (and maybe make it open source / hosted somewhere if someone else needs it later 🙂)

**Comment by syt0r** [comment]
That' ok, I can extract kanji myself. Thanks for clarification regarding levels. I might implement this in the next app version

**Comment by wijourdil** [comment]
Great, thanks a lot! :)

**Comment by syt0r** [comment]
Done, available in version 1.2
