### ISSUE TITLE
Set text locale properly

### ISSUE THREAD

**Issue by ghost** [SYtor/Kanji-Dojo#91]
Some text is displayed in the wrong font if Japanese is not included in system languages. Unihan sucks. It's always you.

Related page: https://heistak.github.io/your-code-displays-japanese-wrong/

<details>
<summary>Workaround</summary>

Add Japanese to system languages (must be above other CJK languages) or:

Run shell commands from adb, Shizuku's rish, App Manager's terminal or elsewhere:
```
adb shell settings delete global settings_app_locale_opt_in_enabled
```
```
adb shell settings put global settings_app_locale_opt_in_enabled false
```

Then set Kanji Dojo's language to Japanese in the app info or per-app language settings.

</details>

![png](https://github.com/syt0r/Kanji-Dojo/assets/147967470/6891257c-cb87-422b-bc7a-6e0a82569043)

**Comment by syt0r** [comment]
Interesting, I have Japanese language as the 3rd language on my device and it shows Japanese version of kanji, but when I removed Japanese language from system settings app switched to Chinese versions

**Comment by martinetd** [comment]
Thanks for that commit, it fixes most of these!

I was about to confirm this fixes the issue on a stock android but tt looks like some text boxes (adding custom set) is still in chinese; most of the other places I checked (reviews etc) are correct now when they weren't though so as far as I'm concerned most of what I see all the time is now correct.

before:
![font](https://github.com/syt0r/Kanji-Dojo/assets/1729331/9de18ea4-8d89-4ac5-970e-b591e0cab7f0)

after:
![font_new](https://github.com/syt0r/Kanji-Dojo/assets/1729331/4360ce3d-7f75-402e-91c7-761cfb21f09f)

**Comment by syt0r** [comment]
@martinetd Oh, that's right, somehow this textfield was using wrong text style, thanks for letting me know
