### ISSUE TITLE
Bug - "Characters Studied" statistic is incorrect 

### ISSUE THREAD

**Issue by polandreh** [SYtor/Kanji-Dojo#98]
My current number of characters studied says 422. It surprised me as it's way higher than I expected, so I went through the painstaking process of manually counting them. I actually know 274.

I made sure that adding kanjis already studied in other practices didn't double-count them.
I also checked if adding new kanjis not yet practiced would flag them as practiced. 

My only suspicion is that practicing a kanji will flag all the radicals as also practiced, even if the characters haven't been studied separately.

**Comment by neithernut** [comment]
Did you count the kanji you studied reading, writing or both independently? (Just had a look at the change, IIUC it should really only count a character as one even if you studied both reading and writing it)

**Comment by polandreh** [comment]
I counted only the Kanji with a green or yellow frame. But I think I know what my issue was: I forgot to count the kana from Hiragana and Katakana, as well as the voiced kanas...

It appears that the count is correct.

**Comment by polandreh** [comment]
It's not a bug. The count is correct.
